spring:
  datasource:
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_LOCAL_URL}
#    url: jdbc:mysql://localhost:3306/replication-test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update